# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections:
  tidbits:
    output:   false

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
#markdown:    kramdown
markdown:    redcarpet
#highlighter: rouge
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
#host:    0.0.0.0
host:    127.0.0.1
# For projects, use the baseurl to set host/[baseurl]/
# http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/
# baseurl: "/project" # does not include hostname
baseurl: ""

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex
#  fenced_code_blocks: true

#rdiscount:
#  extensions: []

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
#  use_coderay:   false

#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style

#redcloth:
#  hard_breaks: true

#pygments:       true
#rouge:          true

sass:
  sass_dir:  _sass
  style:        expanded    # [nested|expanded|compact|compressed]
#  deploy_style: compressed  # [nested|expanded|compact|compressed]

# Setup
title:          rmaicle
tagline:        'What is computable must be immediate so we can spend more time with the incomputable'
description:    'Personal GitHub Page'

author:
  name:         'rmaicle'
  url:          http://rmaicle.github.io/
  github:       http://github.com/rmaicle
  twitter:      https://twitter.com/rmaicle
  wordpress:    http://rmaicle.wordpress.com/

defaults:
  -
    scope:
      path:     "/*.md" # "" means all files in the project
      type:     "pages" # [posts|pages|drafts]
    values:
      layout:   "page"
  -
    scope:
      path:     "" # "" means all files in the project
      type:     "posts" # [posts|pages|drafts]
    values:
      layout:   "post"
  -
    scope:
      path:     "tidbits" # "" means all files in the project
      type:     "tidbits" # [posts|pages|drafts]
    values:
      layout:   "none"
      tidbit:   "true"

# Custom vars
version:        0.1.0

# This is the list of pages to incldue in the header of the website.
pages_list: {
  'Archive':      '/archive.html',
#  'To Read':    '/toread.html',
#  'Blogroll':   '/blogroll.html',
  'DLang':      '/dlang/index.html',
  'References': '/refs.html',
#  'About':      '/about.html',
}

# This is the list of pages under the DLang directory.
dlang_list: {
    'Introduction':                '/dlang/intro.html',
    'Types':                       '/dlang/types.html',
    'Expressions':                 '/dlang/expressions.html',
    'Statements':                  '/dlang/statements.html',
    'Enumerations':                '/dlang/enumerations.html',
    'Arrays':                      '/dlang/arrays.html',
    'Functions':                   '/dlang/functions.html',
    'Structs, Unions and Classes': '/dlang/structs_unions_classes.html',
    'Templates':                   '/dlang/templates.html',

    'Convenience':                 'divider',
    'Modules':                     '/dlang/modules.html',
    'Memory Management':           '/dlang/memory.html',
    'Unit Testing':                '/dlang/testing.html',
    'Embedded Documentation':      '/dlang/embedded_doc.html',

    'Power':                       'divider',
    'Contracts':                   '/dlang/contracts.html',
    'Conditional Compilation':     '/dlang/conditional.html',
    'Mixins':                      '/dlang/mixins.html',
    'Traits':                      '/dlang/traits.html',
    'Compiler Pragmas':            '/dlang/pragmas.html',

    'Efficiency':                  'divider',
    'Memory Alignment':            '/dlang/alignment.html',
    'Concurrency':                 '/dlang/concurrency.html',
    'Interfacing to C':            '/dlang/c_interface.html',
    'Vector Extensions':           '/dlang/vector_ext.html',
    'Inline Assembler':            '/dlang/assembler.html',
}
