# Where things are
source:      .
destination: ./_site
#plugins:    ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
collections:
  tidbits:
  dlangnews:
  dlang_compiler_releases:

# Handling Reading
redirects:    yes
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-feed

# Conversion
markdown:    kramdown
# Rouge 1.10.1 doesn't have the D programming language code highlighter'
# https://github.com/jneen/rouge
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
#host:    0.0.0.0
host:    127.0.0.1
# For projects, use the baseurl to set host/[baseurl]/
# http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/
# baseurl: "/project" # does not include hostname
baseurl: ""

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex
#  fenced_code_blocks: true

#rdiscount:
#  extensions: []

#redcarpet:
#  extensions: ["space_after_headers", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "highlight"]

#kramdown:
#  auto_ids:           true
#  footnote_nr:        1
#  entity_output:      as_char
#  toc_levels:         1..6
#  smart_quotes:       lsquo,rsquo,ldquo,rdquo
#  syntax_highlighter: rouge

#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style

#redcloth:
#  hard_breaks: true
#  pygments:       true
#  rouge:          true

sass:
  sass_dir:      _sass
  style:         expanded    # [nested|expanded|compact|compressed]
#  deploy_style: compressed  # [nested|expanded|compact|compressed]

# Setup
title:          rmaicle.github.io
#tagline:       'What is computable must be immediate so we can spend more time with the incomputable'
tagline:        "Programming is an endless loop; it's either you break or exit."
description:    'Personal GitHub Page'

author:
  name:         'rmaicle'
  url:          http://rmaicle.github.io/
  github:       http://github.com/rmaicle
  twitter:      https://twitter.com/rmaicle
  wordpress:    http://rmaicle.wordpress.com/

defaults:
  -
    scope:
      path:     "/*.md" # "" means all files in the project
      type:     "pages" # [posts|pages|drafts]
    values:
      layout:   "page"
  -
    scope:
      path:     "" # "" means all files in the project
      type:     "posts" # [posts|pages|drafts]
    values:
      layout:   "post"
  -
    scope:
      path:     "tidbits" # "" means all files in the project
      type:     "tidbits" # [posts|pages|drafts]
    values:
      layout:   "none"
      tidbit:   "true"
  -
    scope:
      path:     "dlangnews"
      type:     "dlangnews"
    values:
      layout:     "none"
  -
    scope:
      path:     "dlang_compiler_releases"
      type:     "dlang_compiler_releases"
    values:
      layout:     "none"

# Custom vars
version:        0.1.0

# This is the list of pages to incldue in the header of the website.
pages_list: {
  'Posts':       '/archive.html',
  'DLang':       '/dlang-guide/index.html',
  'DReference':  '/dlang-ref/index.html'
}
