# rmaicle.github.io
# 11 April 2017

image: rmaicle.png
title: rmaicle
email: rmaicle@gmail.com
description: >
  Programming is an endless loop; it's either you break or exit.
twitter_username: rmaicle
github_username: rmaicle
github: http://github.com/rmaicle

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:
  posts:
    output:   true
collections:
  sections:
    output: true
    layout: hub

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
# Atom (RSS) feeds for GitHub Pages
# https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-feed
# Search engine optimization for GitHub Pages
# https://help.github.com/articles/search-engine-optimization-for-github-pages/
  - jekyll-seo-tag
# Redirect visitors to the updated URL
# https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     none
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  
sass:
  sass_dir:      _sass
  style:         expanded    # [nested|expanded|compact|compressed]
  deploy_style:  compressed  # [nested|expanded|compact|compressed]
